import { floatingPanel } from './floating-panel.ts';
/** Presentation and navigation for the assistant; provider state stays in ai-panel. */
export function createAIPanel(desktop: boolean) {
    const toggle = document.createElement('button'); toggle.id = 'ai-toggle'; toggle.className = 'subtle'; toggle.textContent = 'AI';
    toggle.setAttribute('aria-expanded', 'false'); toggle.setAttribute('aria-controls', 'ai-panel');
    document.querySelector('.header-actions')!.prepend(toggle);
    const panel = document.createElement('aside'); panel.id = 'ai-panel'; panel.hidden = true; panel.setAttribute('aria-label', '导演助手');
    panel.innerHTML = `<div id="ai-resize" role="separator" tabindex="0" aria-orientation="horizontal" aria-label="调整助手大小" title="拖动右下角调整大小，方向键微调，双击复位"></div>
<header class="ai-header" title="拖动移动窗口"><div><strong>导演助手</strong><span>编排与检查当前工程</span></div><div class="ai-window-buttons"><button id="ai-collapse" class="icon-button" aria-label="收起导演助手">−</button><button id="ai-close" class="icon-button" aria-label="关闭 AI 面板">×</button></div></header>
<nav class="ai-navigation" aria-label="助手功能"><button id="ai-chat-toggle" data-ai-view="chat" aria-pressed="true">对话</button><button id="ai-settings-toggle" data-ai-view="settings" aria-pressed="false">渠道设置</button><button id="ai-skills-toggle" data-ai-view="skills" aria-pressed="false">技能</button><button id="ai-mcp-toggle" data-ai-view="mcp" aria-pressed="false">MCP 连接</button></nav>
<section id="ai-skills" class="ai-view" hidden></section>
<section id="ai-chat" class="ai-view ai-chat"><div class="ai-controls"><label>渠道<select id="ai-channel" aria-label="AI 渠道"></select></label><label>模式<select id="ai-mode" aria-label="AI 模式"><option value="execute">执行</option><option value="discuss">讨论</option></select></label></div><div class="ai-context-row"><p id="ai-context">按需读取场景数据；图片不自动上传。</p><button id="ai-scene-prompt" class="subtle" type="button">本场提示词</button></div><textarea id="ai-transcript" readonly aria-label="AI 对话与操作记录" placeholder="任务进展和操作结果将显示在这里。"></textarea><label class="ai-prompt-label" for="ai-prompt">当前任务</label><textarea id="ai-prompt" maxlength="20000" placeholder="例如：安排三人的走位，检查运镜和出画情况。" aria-label="AI 任务"></textarea><div class="ai-buttons ai-task-buttons"><button id="ai-send" class="primary">发送</button><button id="ai-stop" disabled>停止</button><button id="ai-new">新对话</button><button id="ai-undo">撤销一步</button></div></section>
<form id="ai-settings" class="ai-view" hidden><div class="ai-settings-fields"><label>编辑渠道<select id="ai-edit-channel"><option value="">新建</option></select></label><label>名称<input id="ai-name" maxlength="80" placeholder="我的渠道"/></label><label>接口协议<select id="ai-protocol"><option value="chat">OpenAI Chat 兼容</option><option value="responses">OpenAI Responses</option><option value="anthropic">Anthropic Messages</option></select></label><label>模型 ID<input id="ai-model" placeholder="模型名称"/></label><label class="ai-full-row">接口地址<input id="ai-url" placeholder="https://api.deepseek.com/v1"/></label><label class="ai-full-row">密钥<input id="ai-key" type="password" autocomplete="off" placeholder="留空保留同渠道密钥"/></label><label class="ai-check"><input id="ai-remember" type="checkbox"/>系统加密保存密钥</label><label class="ai-check"><input id="ai-stream" type="checkbox" checked/>流式响应</label><label>输出 tokens（0 自动）<input id="ai-max-tokens" type="number" min="0" step="1" value="0"/></label><label>任务轮数（0 不限）<input id="ai-max-rounds" type="number" min="0" step="1" value="64"/></label></div><p>输出填 0 自动采用模型额度；轮数填 0 不限。连通测试使用少量 token。</p><div class="ai-buttons"><button type="submit" class="primary">保存渠道</button><button type="button" id="ai-test">连通测试</button><button type="button" id="ai-remove" class="subtle">删除</button></div></form>
<section id="ai-mcp" class="ai-view" hidden><div class="ai-mcp-heading"><label class="ai-check"><input id="ai-mcp-enabled" type="checkbox"/>启用本机 MCP</label><label class="ai-check"><input id="ai-mcp-lan-enabled" type="checkbox" disabled/>允许局域网连接 (同 WiFi)</label></div><p>让外部 Agent 连接当前软件，查询场景、编辑工程并导出文件。</p><div class="ai-connection"><span>本机地址</span><div id="ai-mcp-status">关闭</div></div><div id="ai-mcp-lan-row" class="ai-connection" hidden><span>局域网地址</span><div id="ai-mcp-lan-status">关闭</div></div><label class="field">客户端<select id="ai-mcp-client"><option value="http">通用 HTTP</option><option value="claude-code">Claude Code（CLI / 桌面 Code）</option><option value="claude-desktop">Claude Desktop（聊天）</option><option value="stdio">通用 stdio</option></select></label><p id="ai-mcp-client-help"></p><div class="ai-buttons"><button id="ai-mcp-copy" class="wide subtle" disabled>复制连接配置</button><button id="ai-mcp-lan-copy" class="wide subtle" disabled hidden>复制局域网配置</button></div><button id="ai-mcp-reset" class="wide subtle" disabled>重置连接凭据</button><p>配置保存于本机，重启或重新开启后仍可复用。只有重置凭据后需要重新复制配置。</p></section>
<footer class="ai-footer"><textarea id="ai-status" readonly role="status" aria-label="助手运行状态">${desktop ? '选择渠道后输入任务。' : 'AI 接口与 MCP 在桌面版使用。网页版仍可导入 AI 生成的工程文件。'}</textarea><button id="ai-background-stop" class="subtle" hidden>停止任务</button></footer>`;
    const changes = document.createElement('button'); changes.id = 'ai-changes'; changes.className = 'subtle'; changes.textContent = '修改定位';
    panel.querySelector('.ai-context-row')!.append(changes);
    document.body.append(panel);
    const find = <T extends HTMLElement = HTMLInputElement>(id: string) => panel.querySelector<T>('#' + id)!;
    const windowLayout = floatingPanel(panel, panel.querySelector('.ai-header')!, find('ai-resize'), find<HTMLButtonElement>('ai-collapse'), 'director-ai-window-v1');
    const open = (value: boolean) => { panel.hidden = !value; if (value) windowLayout.refresh(); toggle.setAttribute('aria-expanded', String(value)); if (!value) { panel.querySelector('[data-parent-page-back]')?.remove(); toggle.focus({ preventScroll: true }); } };
    toggle.onclick = () => open(panel.hidden); find('ai-close').onclick = () => open(false);
    const navigate = (view: string) => {
        for (const name of ['chat', 'settings', 'skills', 'mcp']) find(name === 'settings' ? 'ai-settings' : 'ai-' + name).hidden = name !== view;
        panel.querySelectorAll<HTMLElement>('[data-ai-view]').forEach(button => button.setAttribute('aria-pressed', String(button.dataset.aiView === view)));
        panel.dataset.aiPage = view;
    };
    panel.querySelectorAll<HTMLElement>('[data-ai-view]').forEach(button => button.onclick = () => navigate(button.dataset.aiView!));
    panel.addEventListener('keydown', event => { if (event.key === 'Escape' && (event.target as HTMLElement).tagName !== 'SELECT') { event.preventDefault(); event.stopPropagation(); open(false); } });
    navigate('chat');
    return { panel, find, navigate, open };
}
