import type { Project } from '../model.ts';
import { shortVersion as version } from '../../package.json';
import { ASPECTS, FRAME_RATES } from '../model.ts';
import { $, button, icon, options } from './common.ts';
export function mountLayout(project: Project) {
    $('#app').innerHTML = `
<header class="topbar"><div class="brand"><span class="logo">D<span>·</span></span><div><strong>导演台</strong><span class="brand-sub">AI 短剧预演</span></div></div><span class="top-separator"></span><div class="scene-switcher"><select id="scene-switch" aria-label="当前独立戏段"></select>${button('sequence-open', '戏段', '', 'subtle')}${button('production-prompt', '提示词', '', 'subtle', 'id="scene-prompt-toggle" title="展开当前戏段提示词"')}</div><span class="version">版本 ${version}</span><div class="header-actions"><span id="save-status" class="save-status">本地项目</span>${button('undo', '', 'undo', 'icon-button', 'title="撤销 Ctrl+Z"')}${button('redo', '', 'redo', 'icon-button', 'title="重做 Ctrl+Shift+Z"')}<span class="top-separator"></span><select id="aspect" aria-label="项目画幅">${options(ASPECTS.map(a => [a, a]), project.aspect)}</select><select id="fps" aria-label="项目帧率">${options(FRAME_RATES.map(f => [String(f), f + ' fps']), String(project.fps))}</select>${button('open', '打开', 'folder', 'subtle')}${button('save', '保存项目', 'save', 'subtle')}${button('export', '导出视频', 'download', 'primary')}</div></header>
<main class="workspace"><aside class="sidebar"><div id="creation-mode" class="segmented-control" role="group" aria-label="创作模式" title="仅改变 AI 搭建方式，不转换已有场景"><button type="button" data-creation-mode="full" aria-pressed="true">精细模型</button><button type="button" data-creation-mode="geometry" aria-pressed="false">几何体</button></div><nav class="side-tabs"><button data-side="scene" class="active">场景</button><button data-side="assets">资产</button></nav><div class="search-field">${icon('search')}<input id="search" placeholder="搜索场景对象" aria-label="搜索"/><kbd>/</kbd></div><div id="sidebar-content"></div><div class="side-bottom">${button('project', '工程信息', '', 'wide')}${button('scene-templates', '新建工程 / 模板', 'grid', 'wide')}${button('user-motion-library', '用户动作库', 'folder', 'wide')}${button('model-import', '导入模型', 'folder', 'wide') + button('spatial-open', '空间检查', 'search', 'wide')}${button('production-notes', '制作备注 / 素材包', 'folder', 'wide')}${button('add-camera', '添加摄影机', 'camera', 'wide')}${button('lighting-open', '灯光与环境', '', 'wide')}${button('room', '房间尺寸与结构', 'grid', 'wide subtle')}${button('help', '操作指南', 'info', 'subtle wide')}</div></aside>
<section class="center"><div class="view-toolbar">
<div class="view-navigation"><div class="tools" aria-label="变换工具">${button('translate', '', 'move', 'icon-button active', 'title="移动 1"')}${button('rotate', '', 'rotate', 'icon-button', 'title="旋转 2"')}${button('scale', '', 'scale', 'icon-button', 'title="缩放 3"')}</div><div class="view-modes"><button data-view="stage">布景</button><button data-view="split" class="active">并排</button><button data-view="shot">拍摄</button></div><div class="viewport-shortcuts">${button('grid', '米格', 'grid', 'tool-button active')}${button('top', '俯视', '', 'tool-button')}${button('home', '全景', '', 'tool-button', 'title="回到全景"')}</div></div>
<div class="view-editing"><div class="snap-tools"><select id="placement-snap" aria-label="网格吸附" title="移动按所选米数吸附；旋转吸附 15°"><option value="0">网格吸附关</option><option value="0.1">吸附 0.1 m</option><option value="0.5">吸附 0.5 m</option><option value="1">吸附 1 m</option></select><label class="object-snap-toggle" title="移动道具时吸附邻近白模的表面和边界；尊重当前拖动轴"><input id="object-snap" type="checkbox"/>物体吸附</label></div><div class="key-tools"><select id="position-edit-mode" aria-label="位置编辑方式" title="整体平移：移动对象及整条路径；位置关键帧：只记录播放头时刻的位置"><option value="whole">整体平移</option><option value="key">位置关键帧</option></select>${button('position-key', 'K 位置', '', 'subtle', 'title="在当前时间记录位置关键帧 K"')}</div></div></div>
<div class="viewports split" id="viewports"><section class="viewport-panel stage-panel"><div class="panel-topline"><span><i class="status-dot"></i>布景视图</span><span>1 格 = 1 米</span></div><div id="stage-canvas"><div id="object-labels"></div><div id="stage-hint">点击布景启用键盘 · WASD 移动 · QE 转向 · RF 升降</div><div id="room-badge"></div><div id="object-snap-status" role="status"></div></div></section><section class="viewport-panel shot-panel"><div class="panel-topline"><span>${icon('camera')}<b id="shot-name">摄影机</b></span><span id="shot-lens"></span><label class="reference-label-toggle" title="将人物和胶囊占位名称显示在摄影机画面、截图及参考视频中"><input id="reference-labels" type="checkbox"/>视频标签</label></div><div id="shot-canvas"><div class="shot-crosshair" hidden></div></div><div class="shot-bottomline"><span id="shot-time"></span><span id="shot-warning">同场景真实取景</span></div></section></div>
<div class="monitor-strip"><span class="monitor-label">机位监看</span><div id="camera-buttons"></div><div class="monitor-actions">${button('new-from-view', '当前视角建机位', 'camera', 'subtle')}${button('insert-cut', '设为此处镜头', '', 'subtle')}${button('snapshot', '', 'image', 'icon-button', 'title="导出当前机位截图"')}</div></div></section>
<aside class="inspector"><div id="inspector-scope" role="group" aria-label="右侧编辑范围"><button data-act="lighting-open" data-inspector-scope="scene">灯光与场景</button><button data-inspector-scope="selection" aria-pressed="true">当前选中元素</button></div><div id="inspector-header"></div><div id="inspector-tabs"></div><div id="inspector-content"></div><div id="inspector-footer"></div></aside></main>
<section class="timeline"><div class="transport"><div class="transport-playback"><span class="timeline-title">时间轴 <span id="duration-label"></span></span><div class="playback-buttons">${button('begin', '', 'back', 'icon-button', 'title="回到开头"')}${button('prev', 'Ⅰ◂', '', 'icon-button', 'title="上一帧"')}${button('play', '', 'play', 'play-button', 'title="播放 / 暂停 Space"')}${button('next', '', 'step', 'icon-button', 'title="下一帧"')}</div><span id="timecode" class="timecode"></span>${button('loop', '整场循环', '', 'tool-button')}<label class="duration-input">时长<input id="duration" type="number" min=".1" step="1" value="15"/>秒</label></div><div class="transport-editing"><div class="timeline-zoom-controls"><button id="timeline-zoom-out" class="tool-button" aria-label="缩小时间轴">${icon('zoomOut')}</button><select id="timeline-zoom" aria-label="时间轴缩放"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option><option value="8">8×</option><option value="16">16×</option></select><button id="timeline-zoom-in" class="tool-button" aria-label="放大时间轴">${icon('zoomIn')}</button></div><div class="timeline-view-tabs" role="group" aria-label="时间轴内容"><button data-timeline-view="tracks" aria-pressed="true">轨道</button><button data-timeline-view="curves" aria-pressed="false">曲线</button></div><select id="timeline-mode" aria-label="时间轨操作模式" title="拖动时间尺定位；拖动片段编辑时间"><option value="edit">编辑片段</option><option value="preview">悬停预览</option></select><button id="timeline-split" class="tool-button" title="选中片段后在播放头处分割 Ctrl+B">分割</button><button id="timeline-trim" class="tool-button" title="编辑选中片段的开始、结束和时长">片段时长</button><button id="timeline-to-ai" class="tool-button" title="选中片段／人物交给 AI；Ctrl 点选多选，Ctrl 拖时间尺选择范围">交给 AI</button><button id="timeline-center" class="tool-button" title="将播放头滚动到可见区域">定位</button></div></div><div id="timeline-content" class="timeline-content"></div><div id="timeline-curves" hidden></div></section>
<footer class="statusbar"><span id="scene-status"></span><span id="selection-status"></span><button id="reset-layout" title="恢复面板默认宽高">重置布局</button><span>本地编辑 · 米制场景</span></footer><div id="toasts" aria-live="polite"></div><div id="modal-root"></div><input id="project-file" type="file" accept=".director,.json" hidden/>`;
}
