import type { AssetDefinition } from './types.ts';

export type FurnitureStyle = 'chair'|'stool'|'bench'|'armchair'|'sofa'|'barstool'|'lounger'|'table'|'roundtable'|'desk'|'coffeetable'|'counter'|'wardrobe'|'shelf'|'rack'|'bed'|'bunk'|'crib'|'nightstand'|'vanity'|'screen'|'coatstand'|'cabinet'|'sink'|'stove'|'fridge'|'washer'|'toilet'|'bathtub'|'shower'|'partition'|'monitor'|'register'|'lectern'|'blackboard'|'hospitalbed'|'waitingbench'|'vending';
export interface FurnitureSpec { id: string; name: string; group: string; style: FurnitureStyle; width: number; height: number; depth: number; surface?: number; layers?: number; aliases?: string[] }
export const FURNITURE_SPECS: readonly FurnitureSpec[] = [
    {id:'furniture-chair',name:'餐椅',group:'座具',style:'chair',width:.48,height:.9,depth:.5,surface:.45},
    {id:'furniture-stool',name:'凳子',group:'座具',style:'stool',width:.38,height:.44,depth:.38},
    {id:'furniture-bench',name:'长凳',group:'座具',style:'bench',width:1.6,height:.46,depth:.43},
    {id:'furniture-armchair',name:'扶手椅',group:'座具',style:'armchair',width:.65,height:.93,depth:.62,surface:.45},
    {id:'furniture-sofa-single',name:'单人沙发',group:'座具',style:'sofa',width:.92,height:.88,depth:.85,surface:.43},
    {id:'furniture-sofa',name:'多人沙发',group:'座具',style:'sofa',width:2.2,height:.9,depth:.9,surface:.43},
    {id:'furniture-barstool',name:'吧椅',group:'座具',style:'barstool',width:.43,height:.78,depth:.43},
    {id:'furniture-lounger',name:'躺椅',group:'座具',style:'lounger',width:.72,height:.94,depth:1.8,surface:.36},
    {id:'furniture-table',name:'方桌',group:'桌台柜架',style:'table',width:1.4,height:.76,depth:.85},
    {id:'furniture-roundtable',name:'圆桌',group:'桌台柜架',style:'roundtable',width:1.2,height:.75,depth:1.2},
    {id:'furniture-desk',name:'书桌',group:'桌台柜架',style:'desk',width:1.3,height:.75,depth:.65},
    {id:'furniture-coffeetable',name:'茶几',group:'桌台柜架',style:'coffeetable',width:1.05,height:.42,depth:.6},
    {id:'furniture-counter',name:'吧台',group:'桌台柜架',style:'counter',width:2.0,height:1.08,depth:.65},
    {id:'furniture-wardrobe',name:'衣柜 · 可开门',group:'桌台柜架',style:'wardrobe',width:1.5,height:2.1,depth:.58},
    {id:'furniture-bookshelf',name:'书架',group:'桌台柜架',style:'shelf',width:.9,height:1.9,depth:.32,layers:5},
    {id:'furniture-rack',name:'货架',group:'桌台柜架',style:'rack',width:1.2,height:1.8,depth:.55,layers:4},
    {id:'furniture-bed-single',name:'单人床',group:'卧室家具',style:'bed',width:1.0,height:1.0,depth:2.05,surface:.5},
    {id:'furniture-bed-double',name:'双人床 · 可调尺寸',group:'卧室家具',style:'bed',width:1.8,height:1.05,depth:2.1,surface:.52},
    {id:'furniture-bunk',name:'上下铺',group:'卧室家具',style:'bunk',width:1.05,height:1.95,depth:2.1,surface:.45},
    {id:'furniture-crib',name:'婴儿床',group:'卧室家具',style:'crib',width:.72,height:1.05,depth:1.32,surface:.55},
    {id:'furniture-nightstand',name:'床头柜 · 抽屉轮廓',group:'卧室家具',style:'nightstand',width:.48,height:.55,depth:.42},
    {id:'furniture-vanity',name:'梳妆台',group:'卧室家具',style:'vanity',width:1.0,height:1.5,depth:.48,surface:.74},
    {id:'furniture-screen',name:'屏风',group:'卧室家具',style:'screen',width:1.8,height:1.8,depth:.3},
    {id:'furniture-coatstand',name:'衣帽架',group:'卧室家具',style:'coatstand',width:.6,height:1.75,depth:.5},
    {id:'furniture-cabinet',name:'橱柜',group:'厨卫家电',style:'cabinet',width:1.2,height:.88,depth:.6},
    {id:'furniture-sink',name:'水槽',group:'厨卫家电',style:'sink',width:.9,height:.92,depth:.6},
    {id:'furniture-stove',name:'灶台',group:'厨卫家电',style:'stove',width:.75,height:.9,depth:.6},
    {id:'furniture-fridge',name:'冰箱',group:'厨卫家电',style:'fridge',width:.72,height:1.8,depth:.7},
    {id:'furniture-washer',name:'洗衣机',group:'厨卫家电',style:'washer',width:.62,height:.87,depth:.62},
    {id:'furniture-toilet',name:'马桶',group:'厨卫家电',style:'toilet',width:.42,height:.82,depth:.7},
    {id:'furniture-bathtub',name:'浴缸',group:'厨卫家电',style:'bathtub',width:.8,height:.58,depth:1.7},
    {id:'furniture-shower',name:'淋浴隔断',group:'厨卫家电',style:'shower',width:.9,height:2.0,depth:.9},
    {id:'furniture-partition',name:'办公隔断',group:'公共设施',style:'partition',width:1.4,height:1.4,depth:.3},
    {id:'furniture-monitor',name:'电脑显示器',group:'公共设施',style:'monitor',width:.55,height:.42,depth:.2},
    {id:'furniture-register',name:'收银台',group:'公共设施',style:'register',width:1.4,height:1.15,depth:.65,surface:.9},
    {id:'furniture-lectern',name:'讲台',group:'公共设施',style:'lectern',width:.8,height:1.1,depth:.55},
    {id:'furniture-blackboard',name:'黑板',group:'公共设施',style:'blackboard',width:2.0,height:1.8,depth:.45},
    {id:'furniture-hospitalbed',name:'医院床',group:'公共设施',style:'hospitalbed',width:.95,height:1.1,depth:2.1,surface:.68},
    {id:'furniture-waitingbench',name:'候车座椅',group:'公共设施',style:'waitingbench',width:1.8,height:.88,depth:.58,surface:.46},
    {id:'furniture-vending',name:'自动售货机',group:'公共设施',style:'vending',width:1.0,height:1.85,depth:.8},
];
const measure = (label: string, value: number) => ({label,default:value,min:.2,max:20,step:.01,unit:'米'});
export const FURNITURE_ASSETS: readonly AssetDefinition[] = FURNITURE_SPECS.map(s => ({id:s.id,name:s.name,kind:'prop',group:s.group,icon:'⊓',family:'furniture-v1',aliases:s.aliases ?? [s.style],
    capabilities:{rig:'none',actions:[],pose:false,path:true},parameters:{width:measure('主体宽度',s.width),height:measure('主体高度',s.height),depth:measure('主体进深',s.depth),
        ...(s.surface !== undefined ? {surfaceHeight:measure(['bed','bunk','crib','hospitalbed'].includes(s.style)?'床面高度':['vanity','register'].includes(s.style)?'台面高度':'座面高度',s.surface)} : {}),
        ...(s.layers ? {layers:{label:'层板数量',default:s.layers,min:2,max:16,step:1,integer:true}} : {}),
        ...(s.style==='wardrobe'?{opening:{label:'柜门开合',default:0,min:0,max:120,step:1,unit:'度'}}:{})} }));
